config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #Posts
  get 'posts/new'
  get 'posts/view/:id', to: 'posts#view', as: 'posts_view'
  get 'posts/edit/:id', to: 'posts#edit', as: 'posts_edit'
  get 'posts/destroy/:id', to: 'posts#destroy', as: 'posts_destroy'
  get 'posts/myPosts', to: 'posts#findMyPosts', as: 'posts_my_posts'
  get 'posts/likes/:id', to: 'posts#likes', as: 'post_likes'
  get 'posts/myLikes', to: 'posts#findMyLikes', as: 'posts_my_likes'

  post 'posts/create'
  post 'posts/update', to: 'posts#update', as: 'posts_update'
  post 'post/find', to: 'posts#find'
  #Pages
  get 'pages/contact'
  #Root
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
      @posts = Post.all.order(:id)
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :find, :view, :findMyPosts]
  def new
  end

  def upload(uploaded_io)
    name = SecureRandom.uuid + File.extname(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', name), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    return name
  end

  def uploadCloudinary(uploaded_io)
    result = Cloudinary::Uploader.upload(uploaded_io)
    return result["public_id"]
  end

  def create
    post = Post.new(post_params)
    post[:img_name] = uploadCloudinary(params[:post][:img_name]) #Sube Imagen a Cloudinary
    post[:ext] = File.extname(params[:post][:img_name])
    if post.save
      flash[:success] = "Post guardado correctamente"
      redirect_to posts_new_path
    else
      flash[:danger] = "Error al guardar Post"
      redirect_to posts_new_path
    end
  end

  def update
    edit = Post.find_by(id: params[:post][:id])
    edit.title = params[:post][:title]
    edit.description = params[:post][:description]
    if edit.save
      flash[:success] = "Post Editado correctamente"
      redirect_to root_path
    end
  end

  def view
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    deleteCloudinary(params[:id]) #Borrar Imagen en Cloudinary
    if Post.destroy(params[:id])
      flash[:success] = "Post Eliminado correctamente"
      redirect_to root_path
    end
  end

  def deleteCloudinary(id)
    post = Post.find(id)
    Cloudinary::Uploader.destroy(post[:img_name])
  end

  def find
    if params[:search][:find] != ''
      @posts = Post.where("UPPER(title) LIKE ?", '%'+params[:search][:find].upcase+'%')
    else
      @posts = Post.all.order(:id)
    end
    render "pages/index"
  end

  def findMyPosts
    @posts = Post.where("user_id = ?", current_user[:id])
    render "pages/index"
  end

  def findMyLikes
    @posts = Post.joins(:likes).where("likes.user_id = ?", current_user[:id])
    render "pages/index"
  end

  def likes
    like = Like.where(post_id: params[:id], user_id: current_user[:id])
    if like.count == 0
      l = Like.new
      l.post_id = params[:id]
      l.user_id = current_user[:id]
      l.save
    else
      Like.destroy(like[0][:id])
    end
  end

  private
    # Valido los campos permitidos
    def post_params
      params.require(:post).permit(:title, :description, :img_name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<div class="header row">
    <div class="logo">
        <%=link_to image_tag("pinterest.jpg", style:"width:60px; height:50px"), root_path%> 
    </div>
    <div class="barra input-group mb-3">
        <div class="col-sm-9">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-search"></i></span>
                <%= form_for :search, :url => { :action => 'find', :controller => 'posts' }, model: @find do |f|  %>
                    <%= f.text_field :find, class:"form-control", id:"find", placeholder:"Buscar" %>
                <% end %>
            </div>
        </div>
        <div class="col-sm-1">
            <div class="link"><%=link_to "Inicio", root_path%></div>
        </div>
        <% if !user_signed_in? %>
            <div class="col-sm-2">
                <div class="link inicioSesion"><%=link_to "Login", new_user_session_path%></div>
            </div>
        <% else %>
            <div class="col-sm-1">
                <div class="link"><i class="fas fa-user-circle"></i> <%= current_user[:name] %></div>
            </div>
        <% end %>
        <% if user_signed_in? %>
            <div class="col-sm-1">
                <div class="dropdown">
                    <div class="menu" data-toggle="dropdown"><i class="fas fa-ellipsis-h"></i></div>
                    <div class="dropdown-menu">
                        <%= link_to "Nuevo Post", posts_new_path, class:"dropdown-item" %>
                        <%= link_to "Mis Posts", posts_my_posts_path, class:"dropdown-item"  %>
                        <%= link_to "Mis Favoritos", posts_my_likes_path, class:"dropdown-item"  %>
                        <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method='delete'>Cerrar Sesión</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<%= render "layouts/header" %>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<%= render "layouts/header" %>
<div class="index">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="post ">
      <div class="card-columns">
        <% @posts.each do |post| %>
          <div class="card">
            <%=link_to cl_image_tag(post.img_name+post.ext, class: "card-img-top", alt: "Card image"), posts_view_path(post) %>
            <% if user_signed_in? && post.user_id != current_user[:id] %>
              <% if post.likes.where(user_id: current_user[:id]).count == 1 %>
                <div post_id="<%= post.id %>" class="like check">
                  <i class="fas fa-heart"></i>
                </div>
              <% else %>
                <div post_id="<%= post.id %>" class="like uncheck">
                  <i class="far fa-heart"></i>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
</div>
<script>
  $( ".like" ).on( "click", function(e) {
    var post_id = $(this).attr("post_id");
    if($(this).hasClass("uncheck")) {
      $(this).removeClass("uncheck");
      $(this).addClass("check");
      $(this).html("<i class='fas fa-heart'></i>");
    } else {
      $(this).addClass("uncheck");
      $(this).removeClass("check");
      $(this).html("<i class='far fa-heart'></i>");
    }
    $.ajax({url: '<%= root_url+"posts/likes/" %>'+post_id,
      dataType:'JSON'
    });
  });
</script>

app/views/posts/_form.html.erb
<%= form_for :post, :url => { :action => action }, model: @post do |f| %>
    <div class="row">
        <% if action == 'update' %>
            <%= f.hidden_field :id, id:"id" %>
        <% end %>
        <% if action == 'create' %>
            <%= f.hidden_field :user_id, value: current_user[:id] %>
        <% end %>
        <div class="col-sm-6">
            <div class="form-group">
                <%= f.label :Título, for:"titulo" %>
                <%= f.text_field :title, class:"form-control", id:"titulo" %>
            </div>
            <div class="form-group">
                <%= f.label :Descripción, for:"descripcion" %>
                <%= f.text_area :description, class:"form-control", id:"descripcion", rows:15 %>
            </div>
        </div>
        <div class="col-sm-4">
            <% if action == "create" %>
                <div class="form-group">
                    <%= f.label :Imagen, for:"file" %>
                    <%= f.file_field :img_name, class:"form-control", id:"file", accept:"image/*" %>
                </div>
            <% end %>
            <div class="form-group">
                <div id="imagen">
                    <% if action == "update" %>
                        <%= cl_image_tag(@post.img_name+@post.ext,) %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <%= f.submit :Guardar, class:"btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "layouts/header" %>
<div class="edit_post container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <h1>Editar Post</h1>
    <%= render 'posts/form', action: 'update' %>
</div>

app/views/posts/new.html.erb
<%= render "layouts/header" %>
<div class="new_post container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <h1>Nuevo Post</h1>
    <%= render 'posts/form', action: 'create' %>
</div>
<script>
    function filePreview(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#imagen + img').remove();
                $('#imagen').after('<img src="'+e.target.result+'" />');
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#file").change(function() {
        filePreview(this);
    });
</script>

app/views/posts/view.html.erb
<%= render "layouts/header" %>
<div class="view_post container">
    <% if user_signed_in? && current_user[:id] == @post.user_id %>
        <div class="row botones">
            <%=link_to content_tag(:i, '', :class => "fas fa-pencil-alt editar"), posts_edit_path(@post) %></i>
            <%=link_to content_tag(:i, '', :class => "fas fa-trash eliminar"), posts_destroy_path(@post.id), data: { confirm: 'Esta seguro que desea borrar este post?' } %></i>
        </div>
    <% end %>
    <div class="row imagen">
        <%= cl_image_tag(@post.img_name+@post.ext) %>
        <span class="posted_by">Posteado el <%= @post.created_at.to_date %> por <%= @post.user.name %></span>
        <span class="likes"><i class="fas fa-heart"></i> <%= @post.likes.count %></span>
    </div>
    <div class="row titulo"><h1><%= @post.title %></h1></div>
    <div class="row descripcion"><%= @post.description %></div>
</div>